---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-git-sync
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-git-sync
  template:
    metadata:
      labels:
        app: my-git-sync
    spec:
    # コンテナの定義
      containers:
      # 1つ目のコンテナ：nginx
      - name: my-nginx
        image: iac9270752/my-nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: git-sync-volume
          mountPath: /html
       # 2つ目のコンテナ：git-sync
      - name: my-git-sync
        image: iac9270752/git-sync:latest
        volumeMounts:
        - name: git-sync-volume
          mountPath: /sync
        env:
        - name: GIT_SYNC_REPO
        # ここの URL は適当なリポジトリのものに変更する
          value: https://github.com/iac9270752/website.git
        - name: GIT_SYNC_BRANCH
        # ブランチ名も適当なものに変更する
          value: main
        - name: GIT_SYNC_ROOT
          value: /sync
        - name: GIT_SYNC_DEST
          value: html
      volumes:
        - name: git-sync-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-git-sync
  labels:
    app: my-git-sync
spec:
  selector:
    app: my-git-sync
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
